---
name: Stop EC2 actions runner
description: Deregisters and terminates a self-hosted GitHub actions repository runner

inputs:
  aws-region:
    description: AWS region
    required: true
  github-token:
    description: GitHub auth token (PAT with repo scope)
    required: true
  github-repo:
    description: Github repository, e.g. ghost/example
    required: true
  runner-id:
    description: GitHub repository runner id
    required: true
  instance-id:
    description: EC2 instance id
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        runner_id='${{ inputs.runner-id }}'
        instance_id='${{ inputs.instance-id }}'
      
        echo "Deregistering repository runner: $runner_id ..."
        
        gh api -X DELETE -H "Accept: application/vnd.github.v3+json" \
          repos/${{ inputs.github-repo }}/actions/runners/$runner_id || echo "WARN: Failed to deregister runner"
        
        echo "Terminating EC2 instance: $instance_id ..."
        
        aws ec2 terminate-instances --instance-ids "$instance_id" > /dev/null
        
        echo "Repository runner stopped"
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
