---
name: Stop EC2 linux runner
description: Terminates a self-hosted linux actions runner on EC2

inputs:
  aws-region:
    description: AWS region
    required: true
  github-token:
    description: GitHub auth token
    required: true
  runner-id:
    description: GitHub runner id
    required: true
  instance-id:
    description: EC2 instance id
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        runner_id='${{ inputs.runner-id }}'
        instance_id='${{ inputs.instance-id }}'
      
        echo "Deregistering self-hosted runner: $runner_id ..."
        
        gh api -X DELETE -H "Accept: application/vnd.github.v3+json" repos/${{ github.repository }}/actions/runners/$runner_id
        
        echo "Terminating EC2 instance: $instance_id ..."
        
        aws ec2 terminate-instances --instance-ids "$instance_id"
        
        echo "Runner successfully stopped"
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
