---
name: Start EC2 linux runner
description: Starts an EC2-based, self-hosted linux runner

inputs:
  aws-region:
    description: AWS region
    required: true
  aws-access-key-id:
    description: AWS access key ID
    required: true
  aws-secret-access-key:
    description: AWS secret access key
    required: true
  github-token:
    description: GitHub auth token
    required: true
  runner-name:
    description: Runner name
    required: true
  ami-id:
    description: AMI id
    required: true
  instance-type:
    description: EC2 instance type
    required: true
  runner-labels:
    description: Labels attachd to the runner
    required: true
runs:
  using: composite
  steps:
    - name: AWS auth
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.aws-region }}
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        
    - name: Start runner
      shell: bash
      run: |
        gh_token="$(gh api -X POST -H "Accept: application/vnd.github.v3+json" repos/{owner}/{repo}/actions/runners/registration-token | jq -r .token)"
        
        user_data=$(base64 <<HERE
        #!/bin/bash
        actions-runner/config.sh --unattended --name ${{ inputs.runner-name }} --url https://github.com/${{ github.repository }} --token $gh_token --labels ${{ inputs.runner-labels }}
        actions-runner/svc.sh install
        actions-runner/svc.sh start
        HERE
        )

        aws ec2 run-instances \
          --image-id "${{ inputs.ami-id }}" \
          --instance-type "${{ inputs.instance-type }}" \
          --user-data "$user_data"

        # TODO: wait until running
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
