---
name: Start EC2 linux runner
description: Starts an EC2-based, self-hosted linux runner

inputs:
  aws-region:
    description: AWS region
    required: true
  github-token:
    description: GitHub auth token
    required: true
  ami-id:
    description: AMI id
    required: true
  instance-type:
    description: EC2 instance type
    required: true
  runner-name:
    description: Runner name
    required: true
  runner-labels:
    description: Runner labels
    required: false
    default: Linux
  runner-home:
    description: Runner home dir
    required: false
    default: /home/ubuntu/actions-runner
  runner-user:
    description: Runner linux user
    required: false
    default: ubuntu
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        runner_token="$(gh api -X POST -H "Accept: application/vnd.github.v3+json" repos/{owner}/{repo}/actions/runners/registration-token | jq -r .token)"
        
        user_data=$(base64 -w0 <<HERE
        #!/bin/bash
        cd "${{ inputs.runner-home }}"
        sudo -u "${{ inputs.runner-user }}" ./config.sh --unattended --name "${{ inputs.runner-name }}" --url "https://github.com/$GH_REPO" --token "$runner_token" --labels "${{ inputs.runner-labels }}"
        ./svc.sh install "${{ inputs.runner-user }}"
        ./svc.sh start
        HERE
        )

        aws ec2 run-instances \
          --image-id "${{ inputs.ami-id }}" \
          --instance-type "${{ inputs.instance-type }}" \
          --user-data "$user_data"

        # TODO: wait until running and registered
      env:
        GH_REPO: ${{ github.repository }}
        GH_TOKEN: ${{ inputs.github-token }}
        AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
