---
name: Start EC2 linux runner
description: Starts a self-hosted linux runner on EC2

inputs:
  aws-region:
    description: AWS region
    required: true
  github-token:
    description: GitHub auth token
    required: true
  ami-id:
    description: AMI id
    required: true
  instance-type:
    description: EC2 instance type
    required: true
  runner-labels:
    description: Runner labels
    required: false
    default: Linux
  runner-home:
    description: Runner home dir
    required: false
    default: /home/ubuntu/actions-runner
  runner-user:
    description: Runner linux user
    required: false
    default: ubuntu
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        runner_token="$(gh api -X POST -H "Accept: application/vnd.github.v3+json" repos/${{ github.repository }}/actions/runners/registration-token | jq -r .token)"
        
        user_data=$(cat <<HERE
        #!/bin/bash
        cd "${{ inputs.runner-home }}"
        instance_id="\$(curl -s http://169.254.169.254/latest/meta-data/instance-id)"
        sudo -u "${{ inputs.runner-user }}" ./config.sh --unattended --name "\$instance_id" --url "https://github.com/${{ github.repository }}" --token "$runner_token" --labels "${{ inputs.runner-labels }}"
        ./svc.sh install "${{ inputs.runner-user }}"
        ./svc.sh start
        HERE
        )

        instance_id=$(aws ec2 run-instances \
          --image-id "${{ inputs.ami-id }}" \
          --instance-type "${{ inputs.instance-type }}" \
          --user-data "$user_data" \
          --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=GitHub Linux runner}]' \
          | jq -r .Instances[0].InstanceId)

        echo "Started instance: $instance_id"

        # TODO: wait until running and registered
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
